# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bedfd54fbbf883aa5844afb24ebc75ddd3762d52460690d16c65d17567e9d9a35b05f0cc6a9ed15e5470bae876f417a38475f90ef47d6579650935873b1f1166
  # key from google developers API Does not do anything at this point.
  google_key: AIzaSyDk3pqtSdX2zNbk-K2zOt0HqoixosDuUos
test:
  secret_key_base: 85c4d845daf46c5188d97ee353a7c552172e7e0e9261dd859ebf822c863b7b283fa1e002c32cce6ecdd997fbeb1de4f9de593e79c1444784c04bd9c7d6e75f10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <85c4d845daf46c5188d97ee353a7c552172e7e0e9261dd859ebf822c863b7b283fa1e002c32cce6ecdd997fbeb1de4f9de593e79c1444784c04bd9c7d6e75f10
